name: Prevent Pushes After 2 PM

on:
  push:

jobs:
  check_time:
    runs-on: ubuntu-latest
    steps:
      - name: Check the time
        run: |
          current_time=$(date -u +%H%M)
          if [ "$current_time" -ge "1322" ]; then
            echo "It is after 13:22 PM UTC. Pushes are not allowed."
            exit 1
          else
            echo "It is before 13:22 PM UTC. Push allowed."
